import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillTwitterCircle,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkmode, setDarkmode] = useState(false);

  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40  dark:bg-gray-900">
        <section className=" min-h-screen dark:bg-gray-900 ">
          <nav className="py-10 mb-12 flex justify-between dark:bg-gray-900">
            <h1 className="text-xl dark:bg-gray-900 dark:text-white">
              developed by rishi
            </h1>
            <ul className="flex items-center dark:bg-gray-900">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkmode(!darkmode)}
                  className="cursor-pointer text-xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="dark:txt-white bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 dark:bg-gray-900">
            <h2 className=" dark:text-white text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Rishikesh Sharma
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer and designer
            </h3>
            <p className=" dark:text-white text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Doloremque sequi doloribus vitae quo impedit placeat voluptatem,
              enim natus distinctio rem quam quibusdam commodi sed culpa quasi
              quidem optio. Perspiciatis, laborum!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-1 dark:text-white">
            <AiFillLinkedin />
            <AiFillYoutube />
            <AiFillTwitterCircle />
          </div>
          <div className=" dark:bg-gray-900 relative overflow-hidden mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 md:h-96 md:w-96 ">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section className="dark:bg-gray-900 dark:text-white">
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-md py-2 leading-8  text-gray-80  ">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos
              quos, esse magnam voluptatum excepturi eum animi enim vitae
              assumenda consectetur omnis dolorem aut sint consequatur explicabo
              rerum, maxime corrupti laudantium?
              <span className="text-md py-2 leading-8 text-gray-800">
                agencies
              </span>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum quam
              ab similique provident maxime aliquid quos iusto nulla dolores
              molestiae.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-1- rounded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. At
                soluta a nam quisquam quidem sunt autem quos. Eius, modi
                consequuntur.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-1- rounded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. At
                soluta a nam quisquam quidem sunt autem quos. Eius, modi
                consequuntur.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-1- rounded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. At
                soluta a nam quisquam quidem sunt autem quos. Eius, modi
                consequuntur.
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section className="dark:bg-gray-900 dark:text-white">
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8  text-gray-80  ">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos
              quos, esse magnam voluptatum excepturi eum animi enim vitae
              assumenda consectetur omnis dolorem aut sint consequatur explicabo
              rerum, maxime corrupti laudantium?
              <span className="text-md py-2 leading-8 text-gray-800">
                agencies
              </span>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum quam
              ab similique provident maxime aliquid quos iusto nulla dolores
              molestiae.
            </p>
          </div>
          <div className="flex flex-col gap-10 lg:flex-row lg:flex-wrap">
            <div className=" flex-1 basis-1/2">
              <Image
                src={web1}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/2 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
